---
title: "Supplementary Figure - Upsampling theta"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r setup}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(ggpubr)
  library(here)
  library(MASS)
  library(patchwork)
  library(RColorBrewer)
  library(reshape2)
  library(sctransform)
  library(scattermore)
  library(sparseMatrixStats)
  library(Seurat)
})

theme_set(theme_pubr())
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

GetOverdisperion_MLE <- function(y) {
  y.dense <- as.matrix(y)
  theta <- 1 / glmGamPoi::glm_gp(data = y.dense, design = ~1, size_factors = FALSE)$overdispersions
  df <- data.frame(amean = rowMeans(y.dense), gmean = sctransform:::row_gmean(y.dense), theta = theta)
  rownames(df) <- rownames(y)
  return(df)
}
SimulateCounts2 <- function(cm, theta) {
  n_c <- colSums(cm)
  p_g <- rowSums(cm) / (sum(rowSums(cm)))

  mu_cg <- as.matrix(n_c) %*% t(as.matrix(p_g))
  y <- t(rbind(apply(
    X = mu_cg, MARGIN = 2,
    FUN = function(x) rnegbin(n = length(x), mu = mean(x), theta = theta)
  )))
  y <- as(object = y, Class = "dgCMatrix")
  rownames(y) <- rownames(cm)
  colnames(y) <- colnames(cm)
  return(y)
}

GetMu_cg2 <- function(cm) {
  n_c <- colSums(cm)
  p_g <- rowSums(cm) / (sum(rowSums(cm)))

  mu_cg <- as.matrix(n_c) %*% t(as.matrix(p_g))
  return(mu_cg)
}

SimulateCounts_cg2 <- function(cm, mu_cg, theta) {
  y <- t(rbind(apply(
    X = mu_cg, MARGIN = 2,
    FUN = function(x) rnegbin(n = length(x), mu = mean(x), theta = theta)
  )))
  y <- as(object = y, Class = "dgCMatrix")
  rownames(y) <- rownames(cm)
  colnames(y) <- colnames(cm)
  return(y)
}
RunSimulation2_MLE <- function(cm, mu_cg, theta = 100, niterations = 1) {
  pb <- txtProgressBar()


  meanvarfit_results <- list()
  for (i in seq(1, niterations)) {
    y <- SimulateCounts_cg2(
      cm = cm,
      mu_cg = mu_cg,
      theta = theta
    )

    meanvarfit <- MeanVarFit(y)

    df <- GetOverdisperion_MLE(y)
    mle_results <- cbind(meanvarfit, df)

    setTxtProgressBar(pb, i / niterations)
  }
  return(mle_results)
}

RunSimulation2 <- function(cm, mu_cg, theta = 100, niterations = 1) {
  pb <- txtProgressBar()

  sct_results <- list()
  sct2_results <- list()
  meanvarfit_results <- list()
  for (i in seq(1, niterations)) {
    y <- SimulateCounts_cg2(
      cm = cm,
      mu_cg = mu_cg,
      theta = theta
    )

    meanvarfit <- MeanVarFit(y)
    meanvarfit_results[[i]] <- meanvarfit
    vst.out.sct <- vst(umi = y, method = "glmGamPoi", n_genes = 2000, verbosity = 0)
    vst.out.sct2 <- vst(
      umi = y, vst.flavor="v2", n_genes = 2000, 
      verbosity = 0
    )

    sct_results[[i]] <- vst.out.sct
    sct2_results[[i]] <- vst.out.sct2

    setTxtProgressBar(pb, i / niterations)
  }
  return(list(meanvarfit_results = meanvarfit_results, sct_results = sct_results, sct2_results = sct2_results))
}

DoComparisonPlot_MLE <- function(mle_results, theta = 100, col = "amean") {
  p <- ggplot(mle_results, aes_string(col, "theta")) +
    geom_scattermore(pointsize = 1) +
    geom_smooth() +
    geom_hline(yintercept = theta, color = "#e41a1c", linetype = "dashed") +
    geom_vline(xintercept = theta, color = "#377eb8", linetype = "dotted") +
    xlab("Gene mean") +
    ylab(expression(theta)) +
    scale_x_continuous(trans = "log10", breaks = c(0.001, 0.01, 0.1, 1, 10, 100), labels = MASS::rational) +
    scale_y_continuous(trans = "log10", breaks = c(0.001, 0.01, 0.1, 1, 10, 100), labels = MASS::rational) +
    ggtitle(theta)


  return(p)
}
DoComparisonPlot <- function(obj_sct_results, obj_sct2_results, theta = 100, col = "amean", smooth = FALSE) {
  gene_mean <- as.data.frame(obj_sct_results$gene_attr)
  gene_mean$gene <- rownames(gene_mean)
  model_pars_fit <- as.data.frame(obj_sct_results$model_pars_fit)
  colnames(model_pars_fit) <- paste0("SCT-", colnames(model_pars_fit))
  model_pars_fit$gene <- rownames(model_pars_fit)

  model_pars_fit2 <- as.data.frame(obj_sct2_results$model_pars_fit)
  colnames(model_pars_fit2) <- paste0("SCT2-", colnames(model_pars_fit2))
  model_pars_fit2$gene <- rownames(model_pars_fit2)

  combined <- inner_join(gene_mean, model_pars_fit, by = "gene")
  combined <- inner_join(combined, model_pars_fit2)
  combined_melt <- melt(
    data = combined[, c("gene", col, "SCT-theta", "SCT2-theta")],
    id.vars = c("gene", col)
  )
  combined_melt$variable <- gsub("-theta", "", combined_melt$variable)
  p <- ggplot(combined_melt, aes_string(col, "value", color = "variable")) +
    geom_scattermore(pointsize = 1)
  if (smooth) {
    p <- p + geom_smooth()
  }
  p <- p +
    geom_hline(yintercept = theta, color = "#e41a1c", linetype = "dashed") +
    geom_vline(xintercept = theta, color = "#377eb8", linetype = "dotted") +
    xlab("Gene mean") +
    scale_color_manual(values = c("#4daf4a", "#984ea3"), name = "") +
    ylab(expression(theta)) +
    scale_x_continuous(trans = "log10", breaks = c(0.001, 0.01, 0.1, 1, 10, 100), labels = MASS::rational) +
    scale_y_continuous(trans = "log10", breaks = c(0.001, 0.01, 0.1, 1, 10, 100), labels = MASS::rational) +
    ggtitle(theta) + theme_pubr()

  return(p)
}
```


```{r}
set.seed(42)
pbmc.sseq3 <- readRDS(here::here("data", "rds_filtered", "PBMC__Smart-seq3.rds"))
cm.pbmc.sseq3 <- GetAssayData(pbmc.sseq3, assay = "RNA", slot = "counts")
mu_cg.sseq3 <- GetMu_cg2(cm.pbmc.sseq3)

upsampled_mu <- mu_cg.sseq3 * 500
theta <- c(10, 100)
sct_results <- list()
for (theta in c(10, 100)) {
  y <- SimulateCounts_cg2(
    cm = cm.pbmc.sseq3,
    mu_cg = upsampled_mu,
    theta = theta
  )
  upsampled_seu <- CreateSeuratObject(y)
  upsampled_seu <- SCTransform(upsampled_seu, method = "glmGamPoi_offset", exclude_poisson=TRUE, verbose = FALSE)
  df <- SCTResults(upsampled_seu, slot = "feature.attributes")
  df$theta_type <- theta
  df$gene <- rownames(df)
  sct_results[[as.character(theta)]] <- df
}
sct_results_df <- bind_rows(sct_results)
pbmc_results <- read.csv(here::here("output", "snakemake_output/seurat_output/PBMC__Smart-seq3/vst2/gene_attr.csv"))
pbmc_results$theta_type <- "PBMC-ss3"
pbmc_results$gene <- rownames(pbmc_results)
common_cols <- intersect(colnames(pbmc_results), colnames(sct_results_df))
```


```{r}

all_results <- rbind(sct_results_df[, common_cols], pbmc_results[, common_cols])
ss3.knn <- read.csv(here::here("output", "snakemake_output", "metacell_knn_seurat_output/PBMC__Smart-seq3/200/gene_attr.csv"))
ss3.knn$theta_type <- "M20"
ss3.knn$gene <- rownames(ss3.knn)

ss3.knn2 <- read.csv(here::here("output", "snakemake_output", "metacell_knn_seurat_output/PBMC__Smart-seq3/300/gene_attr.csv"))
ss3.knn2$theta_type <- "M14"
ss3.knn2$gene <- rownames(ss3.knn2)

ss3.knn3 <- read.csv(here::here("output", "snakemake_output", "metacell_knn_seurat_output/PBMC__Smart-seq3/400/gene_attr.csv"))
ss3.knn3$theta_type <- "M12"
ss3.knn3$gene <- rownames(ss3.knn3)

df <- rbind(ss3.knn, ss3.knn2, ss3.knn3)
all_results <- rbind(all_results, df[, common_cols])

all_results$theta_type <- as.character(all_results$theta_type)
all_results$theta_type <- factor(all_results$theta_type,
  levels = c("10", "100", "M20", "M14", "M12", "PBMC-ss3")
)

ggplot(all_results, aes(gmean, theta, color = theta_type)) +
  geom_scattermore(pointsize = 1.5) +
  scale_x_continuous(trans = "log10", breaks = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000), labels = MASS::rational) +
  scale_y_continuous(trans = "log10", breaks = c(0.001, 0.01, 0.1, 1, 10, 100), labels = MASS::rational) +
  xlab("Gene mean") +
  ylab(expression(theta)) +
  scale_color_manual(labels = c(
    "10" = expression(paste(theta[sim], "=10")),
    "100" = expression(paste(theta[sim], "=100")),
    "PBMC-ss3" = "Observed",
    "M20" = "M20",
    "M14" = "M14",
    "M12" = "M12"
  ), values = brewer.pal(6, "Paired")) +
  scale_fill_discrete(guide = "none") +
  guides(color = guide_legend(override.aes = list(color = brewer.pal(6, "Paired"), size = 4))) +
  theme_pubr() +
  theme(legend.title = element_blank())

dir.create(here::here("output", "figures"))
ggsave(here::here("output", "figures/pbmc_ss3_vs_simulation.pdf"))
```

```{r}
sessionInfo()
```
